version: 2

sources:
   - name: raw
     schema : gz_raw_data
     description: greenweez raw data
     tables: 
       - name: sales 
         identifier: raw_gz_sales
         description: sales of Greenweez
         tests:
           - unique:
               column_name: "(orders_id || '-' || pdt_id)"
         columns:
           - name: date_date
             description: date of purchase
           - name: orders_id
             description: order identification code
           - name: pdt_id
             description: product identification code
           - name: revenue
             description: revenue by product and order
           - name: quantity
             description: quantity of product sold
       - name : product
         identifier: raw_gz_product
         description: products of Greenweez
         columns:
           - name: products_id
             description: product identification code
             tests:
               - unique
               - not_null
           - name: purchase_price
             description: purchaser price of the product
       - name: ship
         identifier: raw_gz_ship
         description: Greenweez shipping fee, logistic cost and ship cost by order_id
         columns:
           - name: orders_id
             description: order identification code
             tests:
               - unique
               - not_null
           - name: shipping_fee
             description: shipping taxes
           - name: logcost
             description: logistic cost
           - name: ship_cost
             description: shipping cost
       - name: adwords
         identifier: raw_gz_adwords
         description: greenweez ad campaign adwords
         columns:
           - name: date_date
             description: date of the campaign
           - name: paid_source
             description: paid source 
           - name: campaign_key
             description: campaign key code
           - name: camPGN_name
             description: campaign name
           - name: ads_cost
             description: cost of the ads
           - name: impression
             description: number of views of the campaign
           - name: click
             description: number of clicks
       - name: bing
         identifier: raw_gz_bing
         description: greenweez ad campaign bing
         columns:
           - name: date_date
             description: date of the campaign
           - name: paid_source
             description: paid source 
           - name: campaign_key
             description: campaign key code
           - name: camPGN_name
             description: campaign name
           - name: ads_cost
             description: cost of the ads
           - name: impression
             description: number of views of the campaign
           - name: click
             description: number of clicks
       - name: criteo
         identifier: raw_gz_criteo
         description: greenweez ad campaign criteo
         columns:
           - name: date_date
             description: date of the campaign
           - name: paid_source
             description: paid source 
           - name: campaign_key
             description: campaign key code
           - name: camPGN_name
             description: campaign name
           - name: ads_cost
             description: cost of the ads
           - name: impression
             description: number of views of the campaign
           - name: click
             description: number of clicks
       - name: facebook
         identifier: raw_gz_facebook
         description: greenweez ad campaign facebook
         columns:
           - name: date_date
             description: date of the campaign
           - name: paid_source
             description: paid source 
           - name: campaign_key
             description: campaign key code
           - name: camPGN_name
             description: campaign name
           - name: ads_cost
             description: cost of the ads
           - name: impression
             description: number of views of the campaign
           - name: click
             description: number of clicks
models: 
  - name: int_campaigns
    tests:
      - unique:
          column_name: "(campaign_key || '-' || date_date)"
      - not_null:
          column_name: "(campaign_key || '-' || date_date)"
  - name: int_campaigns_day
    tests:
      - unique:
          column_name: date_date
      - not_null:
          column_name: date_date
  